name: Multimodal_XAD
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=py38h578d9bd_0
  - cffi=1.14.6=py38ha65f79e_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - cryptography=37.0.2=py38h2b5fc30_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - pip=22.1.2=py38h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_0
  - setuptools=61.2.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py38_cu116
  - torchvision=0.13.1=py38_cu116
  - typing_extensions=4.3.0=pyha770c72_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - timm
    - wandb
    - absl-py==1.2.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.8
    - async-timeout==4.0.3
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - click==8.1.7
    - colour==0.1.5
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - descartes==1.1.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - efficientnet-pytorch==0.7.0
    - einops==0.7.0
    - entrypoints==0.4
    - executing==0.10.0
    - fastjsonschema==2.16.1
    - fire==0.4.0
    - fonttools==4.35.0
    - frozenlist==1.4.0
    - fsspec==2023.12.1
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - git-repo==1.10.3
    - gitdb==4.0.11
    - github3-py==0.9.6
    - gitpython==3.1.40
    - gogs-client==1.0.6
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - imageio==2.33.0
    - imgaug==0.4.0
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - iopath==0.1.10
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.9.1
    - jupyter==1.0.0
    - jupyter-client==7.3.4
    - jupyter-console==6.4.4
    - jupyter-core==4.11.1
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - lightning==2.1.2
    - lightning-utilities==0.10.0
    - llvmlite==0.39.0
    - lxml==4.9.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.4
    - nbclient==0.6.6
    - nbconvert==6.5.3
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - networkx==3.1
    - notebook==6.4.12
    - numpy==1.24.4
    - nuscenes-devkit==1.1.9
    - oauthlib==3.2.0
    - omegaconf==2.1.2
    - opencv-python==4.6.0.66
    - packaging==21.3
    - palette==0.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - polars==0.14.1
    - portalocker==2.8.2
    - progress==1.6
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybitbucket-fork==0.12.2
    - pycocotools==2.0.7
    - pydeprecate==0.3.2
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - python-git==2018.2.1
    - python-gitlab==4.2.0
    - pytz==2022.2.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==23.2.1
    - qtconsole==5.3.1
    - qtpy==2.2.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - rsa==4.9
    - scikit-image==0.21.0
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - send2trash==1.8.0
    - sentry-sdk==1.38.0
    - setproctitle==1.3.3
    - shapely==1.8.2
    - simplejson==3.19.2
    - smmap==5.0.1
    - soupsieve==2.3.2.post1
    - stack-data==0.4.0
    - tabulate==0.9.0
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==1.1.0
    - terminado==0.15.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2023.7.10
    - tinycss2==1.1.1
    - torchmetrics==1.2.1
    - tornado==6.2
    - tqdm==4.64.0
    - traitlets==5.3.0
    - uritemplate==4.1.1
    - uritemplate-py==3.0.2
    - voluptuous==0.14.1
    - wandb==0.16.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.2.2
    - widgetsnbextension==3.6.1
    - yacs==0.1.8
    - yarl==1.9.4
    - zipp==3.8.1